### ISSUE TITLE
Make PermissionsHandler care about source/protocol

### ISSUE THREAD

**Issue by rakiru** [UltrosBot/Ultros#32]
As it stands, the `permissionHandler.check` method accepts a `source` (channel/user the command was used in) and `protocol`, but only depends on the `caller` (command user) to decide whether they have permission. Permissions should be configurable per protocol, and by source inside each protocol. If protocol is None, it should fall back on the caller's standard perm list. If protocol is not None and source is none, it should fall back to the caller's standard protocol instance perm list. If neither is None, then it uses the caller's protocol instance source perm list. If protocol is None but source is not None, we would either fall back to the standard list, error, or just return False. I'd probably go with the first option at present.

Example permissions file format:

```
groups:
  default:
    options: {}
    permissions: [auth.login, auth.logout, auth.register, auth.passwd]
    protocols:
      irc-esper:
        permissions: [bridge.relay]
        sources:
          '#Ultros': [urls.shorten]
      irc-fgn:
        sources:
          '#test': [urls.title]
users:
  rakiru:
    group: default
    options: {superadmin: true}
    permissions: [urls.title]
    protocols:
      irc-esper:
        permissions: [xkcd.xkcd]
        sources:
          '#Ultros-test': [google.suggest]
```

Also, rename `permissionsHandler` to `PermissionsHandler`.

Not in this ticket, but just as a quick reminder of other things that need done to permissions:
- Inheritance
- Negative nodes? (Would avoid having to specify a permission in dozens of individual places instead of a higher-up place, just because we don't want it in one of the lower places)
- Wildcard nodes? (Possibly not a good idea, but should be discussed)
